### PR TITLE
Code refactoring

### PR DESCRIPTION
**Pull request by CzBuCHi**
refactored code from AutoEngineerPlanner.SetManualStopDistance to its own class (SmartOrdersUtility)

TODO: code still uses values 1001-1012 which no longer make sense ...

### CODE REVIEW

**Comment by narc0tiq** [comment]
Can you even get rid of the magic numbers? The message still has to get from the UI to the movement handler somehow.

As a mitigation, I think you could replace them with numbers like ~~`int.MaxValue - 1000`~~ `float.MaxValue - 1000` to make it a lot less restrictive on what movements you can actually request, but the best solution would be if the `BaseLocomotive` had something like a `Dictionary<string, object>` that you could put some arbitrary data into (or even a `dynamic`), to allow you to pass the specifics through that.

Perhaps I should read up on the available API so we can figure out what to request to make our lives easier.

**Comment by narc0tiq** [comment]
Oh, and the magic numbers definitely look like they could be enum values, either with Harmony transparently translating or with a very simple manual conversion.

**Comment by peterellisjones** [comment]
@narc0tiq  I will remove the magic numbers after reviewing and merging this. They were done as part of my original implementation, but are longer required.

**Comment by CzBuCHi** [comment]
i would change `SmartOrdersUtility.GetDistanceInMeters` signature to 

```cs
float GetDistanceInMeters (
    int switchCount,        // those two repoaces magicNumber
    bool stopBeforeSwitch,  //
    BaseLocomotive locomotive, 
    bool forward, 
    out TrackNode switchNode // scheduler can use this to throw that switch in needed
)
```

sure - UI currently do not support 'stop before Nth switch' (currently not that usefull, but I could use that in my scheduler)

also i dont want to mess with the code until merged .... to make simpler review process

**Comment by narc0tiq** [comment]
> @narc0tiq I will remove the magic numbers after reviewing and merging this. They were done as part of my original implementation, but are longer required.

Ha, ok, I look forward to seeing that (and perhaps contributing in future). I clearly haven't read the code closely enough to tell which part is base game and which part is the SmartOrders patch.

**Comment by peterellisjones** [comment]
Hi @CzBuCHi the refactors are great, but i'm not sure about the new functionality:
* Clear switches under train -> this seems to only clear the first switch under the train
* Clear 1,2,3 & approach 1,2,3 -> these have very different implementations since one looks from the back of the train (clear) and one looks from the front (approach) - I'm worried that even with a tooltip explaining this to users, it's going to be confusing.

**Comment by CzBuCHi** [comment]
ad1) looks like this line is causing it: https://github.com/CzBuCHi/Railroader-SmartOrders/blob/9b74ee0922d7ea1b979a69d70caf212b2774f583/SmartOrders/AI/SmartOrdersUtility.cs#L52 - i think i missunderstood your 1001-1013 magicNumbers ....
ad2) idk how to fix this one ... maybe this? 
image

**Pull request closed without merging**
