### PR TITLE
extracted window resizing to separate mod

### PR DESCRIPTION
**Pull request by CzBuCHi**
mod can be found here [Railroader-CarInspectorResizer](https://github.com/CzBuCHi/Railroader-CarInspectorResizer/tree/v1.0)

reasoning for this is that others can add theyr own stuff to orders tab and do not have to compete with this mod when resizing window.

### CODE REVIEW

**Comment by peterellisjones** [comment]
Hi @CzBuCHi  i think this logic should be enough to resize the window without interfering with other mods 

https://github.com/peterellisjones/Railroader-SmartOrders/blob/master/SmartOrders/HarmonyPatches/CarInspectorPatches.cs#L44-L49

if other mods increase the window height the same way saving the original height and just adding whatever extra pixels they need, then I think this should be sufficient

**Comment by peterellisjones** [comment]
Apologies if I wasn't clear in the comment on your other PR: I wasn't saying I want a dependency on another mod. What I was saying was that any features that are not directly related to the core functionality of this mod (such as resizing windows this mod doesn't use), should be in separate mod that is _independent of this mod_, so that people can easily opt out if eg one mod is broken due to a game version update or similar reason.

**Comment by CzBuCHi** [comment]
but this mod is resizing window: 
https://github.com/peterellisjones/Railroader-SmartOrders/blob/269fcf5e670daf899409cd22d236e09b44ec18b9/SmartOrders/HarmonyPatches/CarInspectorPatches.cs#L49  
that means if any other mod also resize same window, then it will be conflicting with this one .... thats why i createrd separate mod so this conflict is removed ...

**Comment by peterellisjones** [comment]
if another mod does the same resize _before_ this mod, then the value of originalWindowSize will include base game + the additional size the other mod added.   If another does the same _after_ this mod, then the value of the other mod's "originalWindowSize" will be the base game size + the additional 30px added by this mod.

**Comment by CzBuCHi** [comment]
but it will not allow do have window height dinamic based on selected tab:
image

or more preciselly mod author would need to code that ...

**Comment by peterellisjones** [comment]
The base game does not resize windows dynamically to remove blank space, so I'm not sure a mod needs to do that either.

Just having a fixed size increase and a bit of extra blank space on some tabs is "good enough" IMHO and far simpler to implement / less likely to break

**Pull request closed without merging**
