### PR TITLE
add button to see target switch

### PR DESCRIPTION
**Pull request by CzBuCHi**
i didnt want to count the switches, so i added new button to UI, that will nove camera to target switch and renders yellow arrow on it (for 2 seconds)

image

in this case i clicked on button '1' ....

Tooltip may need some tweaks ...

### CODE REVIEW

**Comment by peterellisjones** [comment]
Hi @CzBuCHi thanks for the PR -- I can see it being useful, but I don't think it needs to be so tightly integrated with the "move X switches" concept, since showing the destination is useful any time you are using Yard AI. 

Why not have an option in the settings "show yard AI destinations". When enabled, when you make a Yard AI order of any kind, the arrow appears for a few seconds to indicate the destination. This would also mean you don't need to do any extra clicking to switch from "show mode" to "go mode" -- if you get it wrong you can just quickly issue an order for the next switch

**Comment by CzBuCHi** [comment]
im using it i a way, where i click 'show' button, then select coorect switch by clicking on random numbers and then toggle to 'clear' mode to give actual order ...  this has also nice side-effect that i can detect wrongly toggled switches on the way ...

 i didnt know how to make UI that reasonable, so i dediced to make it this way ...
another idea was this UI :
image

also im moving camera position to the switch (which can be quite far way) ... - i think i could/should remember starting camera position and jump back there after couple of seconds (when arrow dissapear) but tyhat not implemented ...

**Comment by CzBuCHi** [comment]
ok i tweaked code a little bit based on your comment ...

also shorten field labels in settings, so they all have same font size (optional, but longer labels are unreadable for me)

**Comment by peterellisjones** [comment]
Hi @CzBuCHi this is a good idea -- but I think there are still a few issues:

* The draw distance for the arrow is fixed so it can be seen from far away. You may also need to increase its size / brightness etc so it stands out
* Don't move the player's camera -- if enough people ask for this feature, we can consider putting it back, (personally I would never want something moving my camera)
* It is updated to work with any yard AI movement, not just switching
* It it enabled in the settings and defaults to "off"

If these sound too restrictive, or aren't what you had in mind, then please also feel free to build the feature into your own mod -- as long as you aren't changing the yard AI panel then I expect SmartOrders would be compatible with a "show yard AI movements with an arrow" mod.

**Comment by CzBuCHi** [comment]
- tried to tweak arrow image
   (size of that thing is based on distance)
- camera movement commented out
- 'arrow' is pointing to node - move 5 cars will probably end up in middle od segment ...
- ???

**Pull request closed without merging**
